version: "3.7"

services:

  database:
    container_name: realestate_database
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    user: 999:999
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data

  server:
    container_name: realestate_server
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/github.com/patoui/realestate
