version: "3.7"
services:
  database:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/github.com/patoui/realestate
